Introduce `composer cs` command
Yoast/wpseo-news pull request #652
Opened 2020-10-14 11:44 UTC by moorscode

## Context

* Introduces the `composer cs` command; as also present in Yoast SEO

## Summary

This PR can be summarized in the following changelog entry:

* Tooling: introduces the `composer cs` command

## Relevant technical choices:

* Adjusted CS configuration to handle the config folder; inspired on Yoast SEO
* Created a config directory
* Removed the `yoast-configcs` command; which is no longer needed

## Test instructions

This PR can be tested by following these steps:

* Run `composer install`
* Run `composer cs` and get a menu to pick which check you want to perform
* Perform any of the menu options and see them working as expected

Fixes #

2020-10-15 12:38 UTC, hansjovis requested changes
Reviewed and tested this. Some added Composer commands fail since `check-cs-warnings` is not defined (see the commment).

2020-10-15 12:38 UTC, hansjovis commented on composer.json
> +            "@check-cs-warnings --filter=GitStaged"
This command fails, since no `check-cs-warning` command is defined within this `composer.json` file.

In WordPress SEO we have two similar commands. One that shows warnings:
```json
"check-cs-warnings": [
	"@php ./vendor/squizlabs/php_codesniffer/bin/phpcs"
],
```
and one that does not:
```json
"check-cs": [
	"@check-cs-warnings -n"
],
```

Since I am not sure which one we want here (or if we want both), I am going to give this one back to you 😉.

2020-10-15 12:38 UTC, hansjovis commented on config/composer/actions.php
> +		\system( 'composer check-cs-warnings -- ' . \implode( ' ', \array_map( 'escapeshellarg', $php_files ) ), $exit_code );
This fails as well for the same reason: `check-cs-warnings` is not defined.

2020-10-15 13:56 UTC, moorscode commented
Applied code review comments.

2020-10-22 11:39 UTC, johannadevos commented
Acceptance: ✅ 
- [x] All 4 `composer cs` commands run without problems.

2020-10-22 11:47 UTC, merged