Create webpack tooling
Yoast/wpseo-news pull request #673
Opened 2021-02-11 10:32 UTC by JoseeWouters

## Context

* In preparation of the Reactifaction of News, we need Webpack. This PR adds that.

## Summary

This PR can be summarized in the following changelog entry:

* Adds Webpack tooling

## Relevant technical choices:

* I didn't add the latest tool in every case, because of some conflicts. For example: couldn't get it to work with Webpack 5, while it worked almost immediately with Webpack 4.

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

* Test if the several grunt tasks still do the same:
* `grunt webpack:buildDev` and `grunt webpack:buildProd` should build the js file
* `grunt webpack:watch` should watch changes to the file in `js/src`
* `grunt build` should now use `webpack:buildDev`
* `grunt artifact` should create a `js` folder and should not create a `js` file in the `assets` folder

### Test instructions for QA when the code is in the RC

* [ ] QA should use the same steps as above.

QA can test this PR by following these steps:

* This PR should not have any effect for the RC

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

*

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes [P1-333](https://yoast.atlassian.net/browse/P1-333)

2021-02-16 08:06 UTC, igorschoester commented
Merged trunk in here, that should fix Travis

2021-02-16 09:09 UTC, igorschoester requested changes
CR 🏗️ 

Awesome work! 🎉 
Besides the points in the code, I have some more requests for the PR text:
You are missing some technical choices, like:
- Moved the JS files to the `js/src` folder. Built in `js/dist`.
- No longer adding `.min` to the built JS files.

2021-02-16 09:09 UTC, igorschoester commented on .removeable-files
> -assets/admin-page.js
I'm not sure we even need this file anymore. I took a quick look. It is used for our [Wiki repo's `clean_up.sh`](https://github.com/Yoast/Wiki/blob/master/includes/clean_up.sh#L12), which is used in `release.sh`, which is how we release this addon. However, the code does not use this file because it is set up with a [`GRUNT_ARTIFACT` flag in `product_choice.sh`](https://github.com/Yoast/Wiki/blob/master/includes/product_choice.sh#L84).

Perhaps keep it for safety though 😅

2021-02-16 14:22 UTC, JoseeWouters commented on config/grunt/task-config/webpack.js
> +		watch: () => webpackConfig( { environment: "development", watch: true } ),
🍪

2021-02-16 15:26 UTC, JoseeWouters commented on assets/admin-page.js
> -/* global wp */
This code was not used at all anymore.

2021-02-16 15:27 UTC, JoseeWouters commented on .removeable-files
> -assets/admin-page.js
Let's check.

2021-02-17 07:26 UTC, igorschoester approved these changes
CR 👍 

I took the freedom to fix the dependencies arguments for you so it can move through 😄

2021-02-17 13:42 UTC, marijnyoast commented
Acceptance 👍🏻

2021-02-17 13:52 UTC, merged