P1-301 reactify editor
Yoast/wpseo-news pull request #678
Opened 2021-02-25 12:24 UTC by igorschoester

## Context

* Use React for the News tab in the editor.
* Merge the `Exclude` and `Google News`'s (no)index options into one (the latter).

## Summary

This PR can be summarized in the following changelog entry:

* Changes News in the editor.

## Relevant technical choices:

*

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

*

### Test instructions for QA when the code is in the RC

* [ ] QA should use the same steps as above.

QA can test this PR by following these steps:

*

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

*

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [ ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes https://yoast.atlassian.net/browse/P1-301

2021-03-01 15:09 UTC, JoseeWouters requested changes
Some minor improvements needed

2021-03-01 15:09 UTC, JoseeWouters commented on js/src/initializers/initializeSettingsPage.js
> +		<li style={{ listStyle: "none", }}>
Please remove this `li` here.

2021-03-02 10:19 UTC, igorschoester commented on js/src/initializers/initializeSettingsPage.js
> +		<li style={{ listStyle: "none", }}>
As discussed, now replaced by `max-width: 600px` on the `Alert`.

2021-03-03 08:43 UTC, JoseeWouters approved these changes
CR 👍

2021-03-03 14:01 UTC, marijnyoast commented
Acceptance 🥇

2021-03-03 14:01 UTC, merged