P3-362 Move reading of options outside functions called by options cache priming, to avoid loops
Yoast/wpseo-news pull request #680
Opened 2021-03-05 16:23 UTC by enricobattocchi

## Context

* See #660 for description of the issue

## Summary

This PR can be summarized in the following changelog entry:

* Fixes a bug where certain conditions (e.g. using a different admin language) would result in an endless loop.

## Relevant technical choices:

* The loop was caused by the querying of the options cache in functions called hooked to the WP `get_options`. The variables storying the options value were converted to static properties since they are accessed by static methods. This is not optimal, also for testing purposes.

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

* in `Settings` > `General`, install a different language from the default one. Then, switch back to the default language, but this way you will have the chance to select a different language for your user.
* In `Users` > `Profile`, change the language of your account and save
* visit `Appearance` > `Customize` and observe that everythings looks good and you don't get any fatal error for Maximum nested functions or a `Bad gateway` page.

### Test instructions for QA when the code is in the RC

* [x] QA should use the same steps as above.

QA can test this PR by following these steps:

*

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

*

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #660, [P3-362]

2021-03-15 13:43 UTC, d-claassen requested changes

2021-03-15 13:43 UTC, d-claassen commented on classes/wpseo-news.php
> +	public static $included_post_types = [];
Can we keep these new constants (`$included_post_types` and `$excluded_terms`) protected to keep them out of the public api for this class?

2021-03-15 13:43 UTC, d-claassen commented on classes/wpseo-news.php
> +	 * Populates static properties from options so they have to be queries each time we need them.
```suggestion
	 * Populates static properties from options so they don't have to be queried each time we need them.
```

2021-03-15 13:47 UTC, enricobattocchi commented on classes/wpseo-news.php
> +	public static $included_post_types = [];
Sure, will fix!

2021-03-15 13:47 UTC, enricobattocchi commented on classes/wpseo-news.php
> +	 * Populates static properties from options so they have to be queries each time we need them.
Yes, definitely. Thanks!

2021-03-15 13:51 UTC, d-claassen approved these changes
Awesome. CR done! ✅

2021-03-16 11:34 UTC, jcomack commented
Acceptance done 👍

2021-03-16 11:34 UTC, merged